### ISSUE TITLE
Add a way to get the `currentArtboard()` for a page

### ISSUE THREAD

**Issue by bomberstudios** [sketch-hq/SketchAPI#273]
At the moment it's not possible to get that from the API, and I need to use `sketch.getSelectedDocument().selectedPage._object.currentArtboard()` which feels pretty ugly 😅

**Comment by mathieudutour** [comment]
`currentArtboard` feels weird: I expected it to be the artboard selected but it's not really. How about `latestTouchedArtboard` or something similar?

**Comment by christianklotz** [comment]
It does feel weird indeed, closing.
