### ISSUE TITLE
Add more UI input types

### ISSUE THREAD

**Issue by KevinGutowski** [sketch-hq/SketchAPI#316]
It currently looks like this:
<img width="532" alt="screen shot 2018-12-19 at 11 39 56 pm" src="https://user-images.githubusercontent.com/4199296/50270736-6ba7d280-03e7-11e9-8c5b-0cbfa595ce36.png">

It doesn't quite clearly communicate what value you are setting. Perhaps something like the image below would be a bit better as it would let the user at least find out what the min/max values are as well as being able to clearly see what value they have selected.

![slider inputcombo](https://user-images.githubusercontent.com/4199296/50270830-b6c1e580-03e7-11e9-8185-996e57071b3d.png)

**Comment by mathieudutour** [comment]
Indeed, I didn't document it for that reason yet.

In addition to the extremum values, it'd be nice to show the steps (if set)

**Comment by KevinGutowski** [comment]
Ahh gotcha, I won't include it in the post I'm writing up for SketchPlugins about the 53 Beta api changes. Thanks!

**Comment by KevinGutowski** [comment]
Ah, yeah I did see that the other UI inputs commented as todos. Looking at the controls here ([https://developer.apple.com/documentation/appkit/views_and_controls?language=objc](https://developer.apple.com/documentation/appkit/views_and_controls?language=objc)) maybe a Date Picker or Segmented Control? Though, not sure if that is really too useful.

Not entirely sure about the core intention of these but it could be nice to be able to use multiple inputs within a modal (or possibly able to mix and match them). Perhaps thats something to consider at a later time.

> PS: if you want to link to the doc of the develop branch…
Ahh, great! Thanks. 👍

**Comment by lpsBetty** [comment]
It would be awesome to have radio buttons when using `selection`. There is no setting yet to achieve this right?

**Comment by KevinGutowski** [comment]
@lpsBetty Correct, but that should be straightforward to add - I'll see if I can get to adding it in this weekend.

**Comment by christianklotz** [comment]
Closing as there are no plans to add this at this point. However we're looking into better UI integration for 3rd party development…
