### ISSUE TITLE
Add method to store sensitive data

### ISSUE THREAD

**Issue by WCByrne** [sketch-hq/SketchAPI#365]
Security is always good to consider and the simple options available for storing data in a plugin can easily lead to vulnerabilities. 

Pulling from this [forum post](https://sketchplugins.com/d/893-storing-sensitive-data/2) it would be great to add API for setting and getting sensitive data:
```javascript
Settings.secureKey(key)
Settings.setSecureKey(key, value)
```

Best would probably be for this to link into keychain though I'm not sure how well cocoa script with interface with that.

**Comment by mathieudutour** [comment]
That's where I'm at:
```js
function getPluginIdentifier() {
  if (!__command.pluginBundle()) {
    // if we run a script from the Run Script panel, it won't have a bundle
    return 'com.sketchapp.temporary-script'
  }
  return __command.pluginBundle().identifier()
}

function stringToData(s) {
  return NSString.stringWithString(
    getPluginIdentifier()
  ).dataUsingEncoding(NSUTF8StringEncoding)
}

function setSecureKey(key, value) {
  __mocha__.loadFrameworkWithName('Security')

  const query = {
    kSecClass: kSecClassGenericPassword,
    kSecAttrAccount: stringToData(getPluginIdentifier()),
    kSecAttrLabel: stringToData(key),
    kSecValueData: stringToData(value)
  }

  const result = SecItemAdd(query, null)

  const errorMessage = SecCopyErrorMessageString(result, null)
  console.log(errorMessage)
}

setSecureKey('test', 'test')
```

but `query` needs to be a `CFDictionaryRef` which I don't really know how to create in JS 🤔

**Comment by WCByrne** [comment]
I was curious if it would be possible to interact with that API from JS. Is there some way to typecast in Cocoascript? Or, if it can't work in JS are there any Sketch internals that could be used for this?

**Comment by mathieudutour** [comment]
> Is there some way to typecast in Cocoascript?

no, everything is `id`

> are there any Sketch internals that could be used for this?

I think we will need to add some for that yes

**Comment by WCByrne** [comment]
Sounds good. Hope that can make it in sooner than later 🙏

**Comment by WCByrne** [comment]
@mathieudutour Do you think this is something that will be addressed soonish? Our plugin is still a little while out, maybe a month or more but I'm wondering if I should wait or go ahead and figure out another option.

**Comment by mathieudutour** [comment]
we are refactoring the keychain access in Sketch so once it's done, i'll implement this

**Comment by markhorgan** [comment]
>  I'd be curious to know what other plugins with auth do now.

@WCByrne I access the keychain API inside a obj-c framework for my plugin.

**Comment by WCByrne** [comment]
@markhorgan that sounds like the best way at the moment. I'm trying hard to avoid ObjC this time around (currently doing a complete rewrite of our plugin using the JS API and a webview).

**Comment by WCByrne** [comment]
Any progress updates on this?

**Comment by thetw** [comment]
@mathieudutour How is the refactoring of the keychain access going? Are there any news when this feature will be implemented? Soon a year has passed and the feature would be a great enrichment 🚀

**Comment by mathieudutour** [comment]
I don't know, I'm not working at Sketch anymore.

**Comment by WCByrne** [comment]
@christianklotz Any updates? ☝️

**Comment by nadavkaner** [comment]
Any updates here?

**Comment by bomberstudios** [comment]
I've documented a workaround, using `node-keychain`, here: https://sketchplugins.com/d/893-storing-sensitive-data/4

It's not the cleanest solution ever, but it gets the job done without too much hassle until we can add proper support for this on the API.

**Comment by WCByrne** [comment]
@bomberstudios, thanks for sharing. Any idea when built in support might make it in?

**Comment by bomberstudios** [comment]
It's hard to tell, there's a lot of stuff in the backlog and getting those done is not always a straightforward process.

**Comment by christianklotz** [comment]
Closing this for now. There's no way to protect sensitive plugin data from other plugins, see [this explanation](https://sketchplugins.com/d/893-storing-sensitive-data/5) for more detail, defeating the point of providing a keychain abstraction.

**Comment by WCByrne** [comment]
So short of it is, plugins probably shouldn't be storing credentials... 😬
