### ISSUE TITLE
Changing a font doesn’t trigger the TextChanged action

### ISSUE THREAD

**Issue by KevinGutowski** [sketch-hq/SketchAPI#370]
Steps to reproduce:

0. Open Sketch Dev Tools and flip to the actions tab
1. Create a text object
2. Select the text layer
3. Change the font
4. Notice that the TextChanged action isn’t triggered

---

Moreover, you can get the TextChanged event to fire in a slightly confusing manner.

0. Open Sketch Dev Tools and flip to the actions tab
1. Create a text object
2. Select the text layer
3. Enter the edit state of the text layer & highlight some text
4. Change the font
5. Note that the TextChanged event doesn’t fire here
6. Unselect the text layer
7. Note that the TextChanged event does fire right before the HandlerLostFocus/GotFocus

Overall, ideally the TextChanged action fires as soon as you make a font modification. Either just by selecting the text layer & changing some font properties or while in the edit state & changing some font properties.

**Comment by christianklotz** [comment]
This is covered by the `onDocumentChange` handler. This action is not "a real" action anyway and it's more likely this action will be removed instead.
