### ISSUE TITLE
Add action for document version migration

### ISSUE THREAD

**Issue by WCByrne** [sketch-hq/SketchAPI#403]
This is a bit of a stretch but I'm curious. In the past I've needed to make changes to some plugin data stored in a document when something changed in Sketch, could be new APIs, format changes, etc. To do so I always stored the version of Sketch in the document settings when the document first interacted with my plugin after a fresh launch. When setting the new version I could perform any changes if that version as different from the previously stored version.

Would it be possible to call an add an action to notify when a document is migrated? I know sketch does some migrations on open in some cases. I'm thinking this would be similar to the document opened action with some extra information about what version it was migrated from.

**Comment by christianklotz** [comment]
Closing since migration is not built as an action internally. In a roundabout way it would be possible to access raw document data prior to opening, see the Assistants' [`fromFile`](https://github.com/sketch-hq/sketch-assistants/blob/main/packages/utils/src/files/index.ts#L9-L45) implementation.
