### ISSUE TITLE
Action API: Support Selection Changes for Substrings

### ISSUE THREAD

**Issue by KevinGutowski** [sketch-hq/SketchAPI#454]
Currently I can get when a layer selection changes however once a user starts editing the text I have no way of knowing when a user makes a substring selection.

With my plugin I’d like users to be able to make a substring selection apply changes to that substring and when they highlight that selection again later my UI should to reflect the state that of the substrings that they selected.

Here is an example that I am trying to mimic from Keynote:

#### Layer Selection
![Screen Shot 2019-04-08 at 11 00 01 PM](https://user-images.githubusercontent.com/4199296/55776609-2c62c780-5a52-11e9-9d78-e27b3ec17241.png)

#### Substring Selection 1st Part
![Screen Shot 2019-04-08 at 11 00 35 PM](https://user-images.githubusercontent.com/4199296/55776626-397fb680-5a52-11e9-90cb-2545afbae6fd.png)

#### Substring Selection 2nd Part
![Screen Shot 2019-04-08 at 11 00 39 PM](https://user-images.githubusercontent.com/4199296/55776637-413f5b00-5a52-11e9-9766-3fd36cafc956.png)

**Comment by christianklotz** [comment]
Substring editing is not propagated through the layer tree and there are no plans to change that at this point. This rules out to have this captured by the JavaScript API for the time being.
