### ISSUE TITLE
Action API: ArtboardChanged event oldArtboard always "<null>" in version 54

### ISSUE THREAD

**Issue by jan-patrick** [sketch-hq/SketchAPI#455]
I call the action event ["ArtboardChanged"](https://developer.sketch.com/reference/action/ArtboardChanged/) to create a [Artboard History](https://github.com/jan-patrick/sketch_artboard-history). It worked perfectly with the previous released version but with version 54 there seems to be a bug with that event. It still gets called but the "oldArtboard" var is always "<null\>" and by that the event isn't working for me anymore:
`oldArtboard = "<null>";`

**Comment by jan-patrick** [comment]
I happens on both calls (begin and finish)

**Comment by rnmp** [comment]
Second this, just experienced this issue.

**Comment by rnmp** [comment]
@jan-patrick kinda related question btw: does `console.log` output not the actual value but some dictionary that you have to expand every time?

**Comment by christianklotz** [comment]
Closing since we introduced the new `onDocumentChange` handler as a universal way to be notified of document changes, see https://developer.sketch.com/plugins/document-changes which should cover artboards, too
