### ISSUE TITLE
Ability to enable/disable overrides of a symbol

### ISSUE THREAD

**Issue by KevinGutowski** [sketch-hq/SketchAPI#503]
It would be great if I could programmatically control what overrides can and cannot be used.

I want to be able to manage this:
<img width="245" alt="Screen Shot 2019-05-18 at 12 35 13 PM" src="https://user-images.githubusercontent.com/4199296/57974205-70a68900-7969-11e9-98e0-bc8810ec92e8.png">

**Comment by mathieudutour** [comment]
You should be able to set `override.editable` on a symbole master. 

Is it not working?

**Comment by KevinGutowski** [comment]
Ah that seems to be working. I was setting it up incorrectly. Is there a way to control the “Allow Overrides” checkbox? I guess that is more of a nice to have.

**Comment by KevinGutowski** [comment]
I think other people are interested in this functionality and since its so easy to do via the private API it might be nice to get people to use a JS API one instead

https://sketchplugins.com/d/1483-master-control-for-overrides

**Comment by christianklotz** [comment]
Closing since the original request is covered. Leaving a code snippet for reference below:

```js
const { getSelectedDocument } = require('sketch/dom')

let document = getSelectedDocument()
let layer = document.pages[0].layers[0] // assuming first layer is symbol instance

layer.master.overrides[0].editable = false
```

Disabling all overrides is possible iterating over all `overrides` in the JavaScript API using for `forEach` without requiring private API and the convenience method to enable/disable all has not been a major request.
