### ISSUE TITLE
LayersResized.finish can not be triggered

### ISSUE THREAD

**Issue by DrinkingWords** [sketch-hq/SketchAPI#553]
When I change the layer's width or height by property panel, the action 'LayersResized.finish' is not triggered. Is there anyway to listen for a layer resized by property panel ?

**Comment by DrinkingWords** [comment]
If there are two plugins and I register both of them to listen for the same action, both of the code will be  executed when the action is triggered.

**Comment by christianklotz** [comment]
Closing since we introduced the new `onDocumentChange` handler as a universal way to be notified of document changes, see https://developer.sketch.com/plugins/document-changes. Let me know if this works for you.

**Comment by DrinkingWords** [comment]
It works. Thank you so much.
