### ISSUE TITLE
Which action am I using to be notified of the change in theme?

### ISSUE THREAD

**Issue by tianzhen02200059** [sketch-hq/SketchAPI#584]
When I change sketch theme to  dark, I want to change my webview theme to dark at the same time. Which action am I using to be notified of the change in theme?

**Comment by mathieudutour** [comment]
There isn't one yet. See https://sketchplugins.com/d/1315-happy-to-see-my-plugin-functionality-be-updated-because-of-the-js-api

**Comment by christianklotz** [comment]
Closing as there are no plans to add an action for this.
