### ISSUE TITLE
Uploading entire document

### ISSUE THREAD

**Issue by qrpike** [sketch-hq/SketchAPI#60]
I am trying to upload the current sketch file to a URL.

I have looked through all the example code and don't see anything that would get me close to it.

Is there an API I'm not seeing to export the document to ZIP format?

Thanks,

**Comment by christianklotz** [comment]
The `.sketch` file is a ZIP archive, meaning all you need is the document's file path. For more info on the file format see https://developer.sketch.com/file-format/
