### ISSUE TITLE
Sketch Dev Docs: Code example not showing

### ISSUE THREAD

**Issue by KevinGutowski** [sketch-hq/SketchAPI#617]
https://developer.sketch.com/plugins/actions#how-do-i-register-my-plugin-to-listen-for-an-action

<img width="770" alt="Screen Shot 2019-09-03 at 9 36 06 AM" src="https://user-images.githubusercontent.com/4199296/64191851-443a4e00-ce2e-11e9-9ffe-c8eae98fbf4f.png">

The code is there - if I highlight it, I can see it:

<img width="799" alt="Screen Shot 2019-09-03 at 9 36 36 AM" src="https://user-images.githubusercontent.com/4199296/64191876-561bf100-ce2e-11e9-9a41-1a50cb99b7f6.png">

Not entirely sure what’s up there. Some coloring issue perhaps?

**Comment by KevinGutowski** [comment]
One easy way to catch regressions like is to generate visual diffs - dunno if y’all want to consider that for the future. Might be a bit overkill for the dev docs though.

**Comment by bomberstudios** [comment]
Thanks for reporting!

Seems to work fine here, looks like it was a hiccup we've since fixed. Feel free to reopen with more info if it still happens on your side.
