### ISSUE TITLE
Confusion about Shared Styles on Layer

### ISSUE THREAD

**Issue by KevinGutowski** [sketch-hq/SketchAPI#667]
Many people seemed to be confused (myself included) that you set and get a shared style from

```layer.sharedStyle```

See
- https://sketchplugins.com/d/1807-how-can-i-find-out-if-a-layer-style-deviates-from-its-shared-style
- https://sketchplugins.com/d/1810-how-to-get-shared-style-of-symbol-override

Can the documentation be updated so that is properly communicated?

**Comment by mathieudutour** [comment]
Duplicate of https://github.com/sketch-hq/SketchAPI/issues/327

**Comment by christianklotz** [comment]
Closing since it's a duplicate.
