### ISSUE TITLE
Moving all code to TypeScript

### ISSUE THREAD

**Issue by pravdomil** [sketch-hq/SketchAPI#67]
https://github.com/BohemianCoding/SketchAPI/pull/66

**Comment by mathieudutour** [comment]
I set up the tools to compile TS. There is no need to change all the code in one go, we can slowly start to move to typescript. The code is highly dynamic tho, so it's going to be kind of hard I reckon

**Comment by pravdomil** [comment]
do you need some help?

**Comment by mathieudutour** [comment]
Actually I do: any idea how to solve this: https://gist.github.com/mathieudutour/7374e586f1c2743fe201e03581a26ba1?

**Comment by pravdomil** [comment]
well it depends

**Comment by pravdomil** [comment]
well we can have a nice day in Prague and share some programming skills

**Comment by christianklotz** [comment]
While TypeScript certainly has its benefits – and we're embracing TypeScript in other [areas](https://github.com/sketch-hq/sketch-file-format) – there's currently no specific reason to bind a lot of development time converting it. Closing for now.
