### ISSUE TITLE
Update LibraryType to include new enum

### ISSUE THREAD

**Issue by nthState** [sketch-hq/SketchAPI#684]
We have a new enum in the LibraryType that we need to expose, the enum indexing has changed

```
const LibraryTypeMap = {
  0: 'Internal',
  1: 'User', // Is this a library added by a user.
  2: 'Remote', // Is this a library that can be updated using an appcast.
}
```

Change to:

```
const LibraryTypeMap = {
  0: 'Internal',
  1: 'LocalUser', // Previously `User`, is this a library added by a user.
  2: 'RemoteUser', // Previously `Remote`, is this a library that can be updated using an appcast.
  3: 'RemoteTeam', // Is this a library hosted on Sketch for Teams
  4: 'RemoteThirdParty',
}
```

**Comment by jedrichards** [comment]
@christianklotz Do we want to include this in the current sprint?

As for impact to the file format, I'm not sure, but I think this is just a model value used internally within Sketch that never gets serialised to disk.

**Comment by jedrichards** [comment]
@christianklotz Ok I think I've updated this enum in a non-breaking fashion. Usage of the old values will continue to work as before. Not sure how to show a deprecation message though because it's just a static value, there's no function to put a `console.log` onto. (the `libraryType` property is just a getter, not a setter).

**Comment by hamishmcneill** [comment]
@jedrichards the Sketch repo issue is now merged. Does this ticket remain open until docs are updated or published?

**Comment by jedrichards** [comment]
@hamishmcneill Thanks Hamish, maybe sensible to leave it open as a reminder to update the docs and merge our `release/63` branch back into develop.
