### ISSUE TITLE
Delete action not triggered on "Backspace" key press

### ISSUE THREAD

**Issue by lllevski** [sketch-hq/SketchAPI#692]
The [Delete](https://developer.sketch.com/reference/action/delete/) action is not triggered when deleting a layer by pressing the"Backspace" key.

**Comment by christianklotz** [comment]
For any document mutation please use the `onDocumentChange` handler which includes deletions, see https://developer.sketch.com/plugins/document-changes for details.

**Comment by lllevski** [comment]
@christianklotz 
Thank you for your reply!

However, your answer does not satisfy my needs. What I am trying to do is prevent a layer from being deleted. The `onDocumentChanged` handler only notifies for a document change after it has been made.

**Comment by jedrichards** [comment]
I haven't tried it, but could you re-add the deleted object back to the canvas in the `onDocumentChanged` handler?

**Comment by lllevski** [comment]
Yes, you can re-add the object but this is more of a workaround solution. This might work in the case of bringing back a deleted layer but might not work for a more complex logic that should be executed before a document change action occurs.
