### ISSUE TITLE
Fix plugin testing errors on Jenkins

### ISSUE THREAD

**Issue by jedrichards** [sketch-hq/SketchAPI#693]
Errors found in testing:

```
skpm/util
skpm/process
```
https://jm.sketchapp.com:9081/job/PluginTests/131/console
https://sketch.slack.com/archives/C1XG54VRC/p1578312086007200

**Comment by jedrichards** [comment]
@christianklotz I've opened PRs to fix these two issues.

- https://github.com/skpm/process/pull/4
- https://github.com/skpm/util/pull/9

The `skpm/util` failure was simply to fix, it was related to the new smart layout api. The `skpm/process` one also simple to fix, if a little more mysterious.

@InvisiblePixels Can you shed some light on what exactly is happening in the PluginTests Jenkins job? I'm just wondering what needs to happen in order to suppress the alerts we're getting on Slack (e.g. https://sketch.slack.com/archives/C1XG54VRC/p1578458812000100).

I'm guessing the Jenkins job is downloading the latest versions of those npm modules and running `npm run test` on them? So in order to fix things we need to get new versions released? Would be good to confirm though.

**Comment by jedrichards** [comment]
Those two PRs are merged, so let's see if we get an alert on Slack tonight 👀

**Comment by jedrichards** [comment]
Calling this done ...

**Comment by InvisiblePixels** [comment]
Did you still need my input for anything? If so DM me :)

**Comment by jedrichards** [comment]
@InvisiblePixels No, all good thanks! 👍
