### ISSUE TITLE
Setting corner radius of ShapePath doesn't work

### ISSUE THREAD

**Issue by lllevski** [sketch-hq/SketchAPI#695]
When setting the corner radius for all the points of a ShapePath the new value is not applied for cornerRadius value under 3.

Steps to reproduce:

1. Create a Rectangle
2. Select it
3. Execute sample code
Sample code:
```
var sketch = require('sketch/dom');
var selectedLayer = sketch.fromNative(context.selection[0]);
var radius = 1;

if (selectedLayer.points && selectedLayer.points.length) {
    selectedLayer.points.forEach(p => p.cornerRadius = radius);
}
```

After executing the sample code the Rectangle has Radius of 3 not 1.

NOTE:

The above example works correctly when replacing this line
`selectedLayer.points.forEach(p => p. cornerRadius = radius);`
with
`selectedLayer.points.forEach(p => p.sketchObject.setCornerRadius(radius));`

**Comment by bomberstudios** [comment]
Hi there, thanks for opening an issue.

I just tried your sample code in Sketch 63, and it seems to be working as expected (i.e: the radius is set to 1, not 3).

Could you please confirm you're still experiencing this issue?

**Comment by lllevski** [comment]
The issue is not reproducible in Sketch 63 from my side too.

**Comment by bomberstudios** [comment]
Closing this, then. Thanks!
