### ISSUE TITLE
Can I get all the font styles in one text layer?

### ISSUE THREAD

**Issue by notzheng** [sketch-hq/SketchAPI#696]
If I use different text style in one text layer, how can I get all the styles?

for example:
![image](https://user-images.githubusercontent.com/13414731/72418313-8b115a80-37b5-11ea-88cc-a4ec01ef1dab.png)

and the sketch js api returns:

![image](https://user-images.githubusercontent.com/13414731/72418367-a9775600-37b5-11ea-92af-25836425f3c3.png)

it seems to that I can get them from nativeObject

![image](https://user-images.githubusercontent.com/13414731/72418501-eba09780-37b5-11ea-870c-ca0603b24383.png)

and it is a simple way to get them?

**Comment by christianklotz** [comment]
Internally this is using `NSAttributedString` and the only way to find out about all styles is by introspecting `attributes`. Please see the following links for more details:

- https://developer.apple.com/documentation/foundation/nsattributedstring
- https://developer.apple.com/documentation/foundation/nsattributedstring/key

**Comment by KevinGutowski** [comment]
I have some experience with your problem. Here is a snippet from one of my plugins that tries to get the various Fonts from a text layer object:

https://github.com/KevinGutowski/betterTypePanel/blob/master/src/my-command.js#L1107

essentially it can be done with something like this:

```
let fonts = []
let textLayer = your_text_layer
let msTextLayer = your_text_layer.sketchObject
let mutableAttrString = msTextLayer.attributedStringValue()
let selectedRange = NSMakeRange(0,textLayer.text.length)

while (selectedRange.length > 0) {
        let font = mutableAttrString.attribute_atIndex_longestEffectiveRange_inRange(
            NSFontAttributeName,
            selectedRange.location,
            effectiveRange,
            selectedRange
        )
        selectedRange = NSMakeRange(
            NSMaxRange(effectiveRange.value()),
            NSMaxRange(selectedRange) - NSMaxRange(effectiveRange.value())
        )

        fonts.push({"font": font, "range": effectiveRange.value()})
    }
 ```

I haven't had a chance to check whether this abstracted code works but that's pretty much the skeleton/approach for getting an array of fonts within a select Text Layer.
