### ISSUE TITLE
cannot specify filename with sketch.export()

### ISSUE THREAD

**Issue by qjebbs** [sketch-hq/SketchAPI#715]
Considering following code, who exports images which is referenced later, so I need specific names which is assigned by myself. But the `output` takes `option.output` as a directory.

```ts
export function export(layer: Layer, format: MyExportFormat, path: string, name: string) {
    let savePath = [
        path, "/",
        format.prefix, name, format.suffix,
        ".", format.format
    ].join("");
    // cannot use sketch.export because it's option.output is a directory, 
    // we don't have a chance to specify the filename,
    // the filename is unpredictable.
    sketch.export(layer,{
        output: savePath,
        formats: format.format,
        scales: format.scale.toString(),
    })
    return savePath;
}
```

**Comment by bomberstudios** [comment]
Good one! Will think about it.

**Comment by christianklotz** [comment]
The file name is based on the layer name, same principle as used by manual Sketch export.

```js
const sketch = require('sketch/dom')
const layer = sketch.getSelectedDocument().pages[0].layers[0]

sketch.export(layer, {
  formats: 'png',
  output: `~/Desktop/`
})
```

- **Layer name:** _Rectangle_ › `~/Desktop/Rectangle.png`
- **Layer name:** _Foo/Rectangle_ › `~/Desktop/Foo/Rectangle.png`

This is by design. You can also use the layer id, see [documentation](https://developer.sketch.com/reference/api/#export) for details.

**Comment by qjebbs** [comment]
Of course I know it's based on the layer name, and more, the scale. But my point is, I need customize the export file name. 

Currently to do so:

1. I have to understand you naming logic, spell the name like `name@2x.png`, then rename it. But what if you add new logic to it?
1. Or, I export to Buffer, and then write to file. But what if the file is too large to be kept in memory?

Why cannot we do it straight? I tell the `export()` the name, it export in the right place.

**Comment by qjebbs** [comment]
If you worry about the compatible issue of filename option against multiple export file cases, the filename takes effect only when export a single file, just like some option is valid only for png export.

**Comment by christianklotz** [comment]
Instead of keeping the file entirely in a buffer, would [`stream`](https://github.com/skpm/stream) be an option?

**Comment by qjebbs** [comment]
@christianklotz Thanks for the quick reply. Can you give an example how `sketch.export()` works with `stream`?

**Comment by commonpike** [comment]
`layer.name` is apparently not readonly, so what i did is save the original name, shortly rename the layer to the required output filename (without the extension), export, and name the layer back to its original name :-)

that's ... ugly. but it worked. So, without testing 

```js
export function export(layer: Layer, format: MyExportFormat, path: string, name: string) {
    let fileName = [
        format.prefix, name, format.suffix
    ].join("");
    var orgName = layer.name;
    layer.name = fileName;
    sketch.export(layer,{
        output: path,
        formats: format.format,
        scales: format.scale.toString(),
    })
    layer.name = orgName;
    // return savePath; -- well, this is still unpredictable
}
```
