### ISSUE TITLE
fromNative Layers do not have the property 'type'

### ISSUE THREAD

**Issue by qjebbs** [sketch-hq/SketchAPI#716]
Use following code to reproduce:

```ts
let target: Artboard = sketch.getSelectedDocument().pages[0].layers[0] as Artboard;
let layerObject: any;
let layerObjects = target.sketchObject.children().objectEnumerator();
while (layerObject = layerObjects.nextObject()) {
    // fromNative Layers do not have the property 'type'
    let child = sketch.Layer.fromNative(layerObject);
    console.log(child.type) //undefined
}
```

**Comment by bomberstudios** [comment]
Thanks a lot for the report spree 🙌

This one is interesting, but I’m not sure it’s technically a bug…

According to [our docs](https://developer.sketch.com/reference/api/#fromnative), you should be doing `let child = sketch.fromNative(layerObject);` to let the API determine the right type for the layer.

I agree it’s a bit surprising that it doesn’t work when you use `sketch.Layer.fromNative`, but keep in mind that `Layer` is really an abstract class we use internally and it doesn’t actually represent anything.

You could technically call `.fromNative` with classes that _do_ represent actual layer types (for example, doing `sketch.Artboard.fromNative(nativeArtboardObject)` works fine and returns an API object with the proper `type` set). But to save you the trouble of checking which class to use for each object type, we give you `sketch.fromNative`, which works out of the box for pretty much anything you throw at it.

Let me know if this makes sense so I can close the issue (and again, thanks for the report!)

**Comment by qjebbs** [comment]
Thanks for your detailed reply.

My problem is solved, this issue can be closed for me. 

But I'd like to say, if the Layer is abstract, represent for all, then the `sketch.Layer.fromNative` works for all layer objects would be more intuitive.

**Comment by bomberstudios** [comment]
That makes sense. I’ll see if I can make that work without over complicating the code.

Thanks!

**Comment by christianklotz** [comment]
Closing for now since the utility was specifically designed to cover all types. I understand that in this particular case it might have been more convenient but the general idea is to keep the API footprint as small as possible.
