### ISSUE TITLE
syncWithSharedStyle Errors should provide more detail

### ISSUE THREAD

**Issue by lucastobrazil** [sketch-hq/SketchAPI#719]
When running syncWithSharedStyle, if the function attempts to update a sharedStyle that is linked to an external library, it returns an error message. 

<img width="644" alt="Screenshot 2020-04-04 at 23 59 56" src="https://user-images.githubusercontent.com/8508891/78462223-68198700-76d0-11ea-8eaa-cabed2c712be.png">

It would be useful to actually show the details of what that sharedStyle actually was, so that the user could track down the culprit.

I have opened a PR #718 

Hope this helps!

**Comment by mathieudutour** [comment]
IMO I'd be even more useful to provide a way to fix in the error message, maybe something like:

	Can not set the style of a shared style coming from a library.
	
	Perhaps you need to check if the shared style is from a library before setting its style:
	```
	if (!sharedStyle.getLibrary()) {
	  sharedStyle.style = newStyle
	}
	```

**Comment by lucastobrazil** [comment]
Yes that’s an interesting solution. Honestly I didn’t even know that that
function existed.

However in my case, I actually want to pinpoint exactly which element is
connected to a shared library so that I can remove it.

The end result I would like is to actually update all of the styles. The
problem I am facing is because I have two copies of a library and one I
maintaining and the other is the master. Sometimes things get a bit
confused where my working version is actually referencing styles in the
master copy.

But I would like them only to reference the working version.

**Comment by mathieudutour** [comment]
right, but even in that case, you can use the code example to do what you want:
```
if (sharedStyle.getLibrary()) {
  // remove it or whatever
}
```

**Comment by lucastobrazil** [comment]
FWIW: I ended up just calling the `sharedStyle.unlinkFromLibrary()` method on whichever styles were linked.
