### ISSUE TITLE
fromSketchJSON is broken

### ISSUE THREAD

**Issue by WCByrne** [sketch-hq/SketchAPI#722]
It's possible I'm lookin in the wrong place but it looks like this line didn't get updated to the new function name: https://github.com/sketch-hq/SketchAPI/blob/e794c0e4a1961b2cad0f8c6d1ef37b7de3a54ab5/Source/dom/export.js#L236

As far as I can tell
 
`MSJSONDictionaryUnarchiver.unarchiveObjectFromDictionary_asVersion_corruptionDetected_error` was updated to `MSJSONDictionaryUnarchiver.unarchivedObjectFromDictionary_asVersion_corruptionDetected_error` in Sketch 64. 4  

Isn't a major goal of this API, to ensure minor internal changes don't break the plugins? It does look like there is a test for this API function, I'm confused how something like this could slip through.

**Comment by WCByrne** [comment]
I'd be happy to post a PR if this is in fact broken

**Comment by jedrichards** [comment]
Thanks for the report. You're right this should have been caught by the tests. We'll look into it!

**Comment by WCByrne** [comment]
Any ETA on a fix for this? Will it get into 65?

**Comment by jedrichards** [comment]
As you probably saw Sketch 65 is out. This issue is in our backlog though, and we'll look at it while figuring out why the tests didn't catch it. We can release fixes to the JS API in Sketch point releases as well though.

**Comment by WCByrne** [comment]
Got it. Getting the CI fixed is nice but this fix in particular is just a few characters. 

As I said before, I'm happy to post a PR if that helps move it along. Unfortunately my plugin depends on this function so sooner would be great.

**Comment by jedrichards** [comment]
Internal resources are focussed elsewhere at the moment, but we're hoping to carve out some time to look at this next week. By all means PR, that will certainly help us out 👍

**Comment by bomberstudios** [comment]
I just merged a fix, and will be published in 65.1. Closing!

**Comment by WCByrne** [comment]
Thank you! Much appreciated.
