### ISSUE TITLE
Typescript definitions?

### ISSUE THREAD

**Issue by endquote** [sketch-hq/SketchAPI#728]
I'm curious if these exist or if there are plans to provide them. It looks like there's [a little something going on here](https://github.com/sketch-hq/SketchAPI/tree/develop/types)?

**Comment by qjebbs** [comment]
https://github.com/qjebbs/sketch.d.ts

**Comment by jedrichards** [comment]
There are no immediate plans to add TypeScript types to the SketchAPI repo, although I agree it'd be nice to have them. It's simply a question of resources and priorities at the moment. For the time being I'd suggest trying the non-official ones, and contributing to those if you find any inconsistencies.

**Comment by endquote** [comment]
Please consider official support, [as your main competitor has](https://www.figma.com/plugin-docs/typescript/).

**Comment by jedrichards** [comment]
We do consider it very important, but as I said it's a question of resources. All new open source projects we're producing will be TypeScript first, for example the [File Format](https://github.com/sketch-hq/sketch-file-format-ts), but with a small team it's not always a simple or maintainable task to retrofit TypeScript onto projects that were created before that technology was as popular as it is now. The ambition for the SketchAPI was always to engage the community, so if you'd like to propose an approach and help with adding TypeScript to this repo we'd be all ears.
