### ISSUE TITLE
Reinstate CurvePoint tests

### ISSUE THREAD

**Issue by bomberstudios** [sketch-hq/SketchAPI#735]
CurvePoint tests seemed brittle and were failing, so were disabled as part of the spring clean. Look at checking them over and reinstating.

Related #732

**Comment by jedrichards** [comment]
Shall we skip the tests or comment them out?

**Comment by bomberstudios** [comment]
They don't even run in Jenkins (they're behind a `if (!isRunningOnJenkins()) {` check) so they wouldn't be blocking the release even if they worked properly.
