### ISSUE TITLE
smartLayout api is not working

### ISSUE THREAD

**Issue by janily** [sketch-hq/SketchAPI#738]
i want to write script,when selected a button group,apply smartlayout.but not working,here is my code,what the problem:

``` let sketch = require('sketch')
let doc = sketch.getSelectedDocument()
let selectedLayersObject = doc.selectedLayers
let selectedLayersArray = selectedLayersObject.layers
const SmartLayout = require('sketch').SmartLayout

selectedLayersArray.forEach(layer => {
  layer.smartLayout = SmartLayout.HorizontallyCenter
});

**Comment by jedrichards** [comment]
You need to call `resizeWithSmartLayout()` on the layer after setting the smart layout to trigger the resize. More info in the docs https://developer.sketch.com/reference/api/#smartlayout.

**Comment by janily** [comment]
thanks,i  call resizeWithSmartLayout() on the layer after setting the smart layout,but it is still not working.
<img width="622" alt="屏幕快照 2020-05-04 上午10 12 30" src="https://user-images.githubusercontent.com/1013557/80931980-c9c43280-8def-11ea-8316-bfe5efbe6c94.png">
 here is my sketch file structure:

<img width="673" alt="屏幕快照 2020-05-03 下午10 44 59" src="https://user-images.githubusercontent.com/1013557/80932027-0001b200-8df0-11ea-95cf-0f0ebe4323c8.png">

**Comment by janily** [comment]
> You need to call `resizeWithSmartLayout()` on the layer after setting the smart layout to trigger the resize. More info in the docs https://developer.sketch.com/reference/api/#smartlayout.

thanks,i  call resizeWithSmartLayout() on the layer after setting the smart layout,but it is still not working.
<img width="622" alt="屏幕快照 2020-05-04 上午10 12 30" src="https://user-images.githubusercontent.com/1013557/80931980-c9c43280-8def-11ea-8316-bfe5efbe6c94.png">
 here is my sketch file structure:

<img width="673" alt="屏幕快照 2020-05-03 下午10 44 59" src="https://user-images.githubusercontent.com/1013557/80932027-0001b200-8df0-11ea-95cf-0f0ebe4323c8.png">

**Comment by jedrichards** [comment]
Looks like you're trying to do smart layout on a group - that isn't going to work, since smart layouts only work with symbols and their instances.

```js
const SmartLayout = require('sketch').SmartLayout
// Set the smart layout on a symbol master
symbolMaster.smartLayout = SmartLayout.TopToBottom
// Trigger the resize on one of its instances
symbolInstance.resizeWithSmartLayout()
```
