### ISSUE TITLE
Data Supplier - Nested menu items

### ISSUE THREAD

**Issue by pete-hotchkiss** [sketch-hq/SketchAPI#741]
When creating a DataSupplier plugin - registering each supplier with it's appropriate appellation in the `DataSupplier.registerDataSupplier` creates everything on the same level.

I'm wondering if it's possible to create nested menu structures here

eg 
```
Data Plugin
  > Fruit
     > data set 1
     > data set 2
 > Vedge
    > data set 3
    > data set 4
```
I've tried adding via the _menu_ option in the `manifest.json` file - but no dice

**Comment by thetw** [comment]
Some time ago i've faced the same problem, here's an undocumentated trick to achieve nested menu structures: 

The registration handler of a DataSupplier recieves three parameters: 
`dataType`, `dataName` and `action`.
```js
  DataSupplier.registerDataSupplier(
    'public.text',
    'Firstname_Female',
    'SupplyRandomFemaleFirstName'
  );
```
If you use an underscore in your `dataName` identifier, which will be  _used as the menu item title for the data_, Sketch automatically splits your `dataName` string at the underscore and creates the desired sub-menu with the second part of your name string as the menu title.

Example result:
![sketch_datasupplier_submenu](https://user-images.githubusercontent.com/36477090/81585218-21483c80-93b4-11ea-934d-2d894425730c.jpg)

**Comment by pete-hotchkiss** [comment]
oooo nice - thanks for the tip
