### ISSUE TITLE
`setLayerSettingForKey()` doesn't work on Overrides or DataOverrides

### ISSUE THREAD

**Issue by oscarmarcelo** [sketch-hq/SketchAPI#750]
`setLayerSettingForKey()` on a layer works just fine, but using it on an Override/DataOverride throws an error.

According to the [documentation](https://developer.sketch.com/reference/api/#set-a-layer-setting), this should work.

## Reproduction (using Sketch DevTools)

1. Create a symbol with a text override;
2. Create a symbol instance and select it;
3. Set a Layer Setting to the override:
```js
const override = sketch.getSelectedDocument().selectedLayers.layers[0].overrides[0];
sketch.Settings.setLayerSettingforKey(override, 'key', 'value');
```

Throws `setValue:forKey:onObject:forPluginIdentifier: requires non-nil values for key, layer and pluginIdentifier`

**Comment by christianklotz** [comment]
Settings only work directly on layers. Override values don't include the `userInfo` attribute as [per file spec](https://github.com/sketch-hq/sketch-file-format/blob/master/schema/objects/override-value.schema.yaml).

**Comment by oscarmarcelo** [comment]
That's what I thought.

May I suggest that [documentation](https://developer.sketch.com/reference/api/#set-a-layer-setting) should be updated to say that only Layer is supported, not DataOverride and Override. 🙂
