### ISSUE TITLE
What is the state and roadmap for this API 

### ISSUE THREAD

**Issue by gregkerzhner** [sketch-hq/SketchAPI#759]
Dear Sketch,

Greg Kerzhner here from InVision.  We are currently exploring using this API for our Craft plugins instead of relying on your private headers which change often.  However, by briefly browsing this repo, its not clear what state this API is in.  The docs say "its still very much a work in progress".  Is it in alpha, beta, or are parts of it ready to be used in production.  Is there a road map and timeline for getting this API production already? Are others already using it in production?  

Thanks!
Greg

**Comment by christianklotz** [comment]
Many plugins are using this API, some keep relying on native frameworks for full flexibility and to achieve things that are not covered by this. It would be great to hear more about your specific requirements, feel free to drop an email to developer@sketch.com and we can take it from there?
