### ISSUE TITLE
Expose changeInstanceToSymbol method

### ISSUE THREAD

**Issue by KevinGutowski** [sketch-hq/SketchAPI#768]
It's annoying to swap symbol instances with the JS API. It would be great if more helper methods like `changeInstanceToSymbol` were exposed so that it can be easier to programmatically recreate functionality in Sketch

See post here: https://sketchplugins.com/d/993-get-all-masters-from-library/5

**Comment by rodionovd** [comment]
Hm, looks like this method is already exposed indirectly via `SymbolInstance.master` setter: https://github.com/sketch-hq/SketchAPI/blob/develop/Source/dom/layers/SymbolInstance.js#L130

so you can do something like

```js
let sketch = require('sketch')
let doc = sketch.getSelectedDocument()
let selection = doc.selectedLayers.layers[0]

let symbols = doc.getSymbols()
let newSymbol = symbols.find(symbol => symbol.name = "B")
selection.master = newSymbol
```

**Comment by christianklotz** [comment]
Indeed, small typo though, it should be `symbol.name == "B"`, not `=`. But otherwise yeah, setting master is the way to swap it.
