### ISSUE TITLE
RESTT API

### ISSUE THREAD

**Issue by KlausSchaefers** [sketch-hq/SketchAPI#779]
Hi,

we are building a low code component, and would like to support Sketch next to Figma. It would be great if there would be a simple REST API to download pre-rendered elements, in particular for vector elements that would be very useful. Figma has a very simple API, you could take it as an example. 

Of course this would only work for projects that are in the Sketch Cloud, but that's ok. 

Thanks,

Klaus

**Comment by rodionovd** [comment]
AFAIK, there's a [`fetch` polyfill](https://github.com/skpm/sketch-polyfill-fetch) which is available automatically if you build your plugins with `skpm`. Usage example [here](https://sketchplugins.com/d/2109-import-svg-from-http/6).

But it would be great to see this fetch API actually documented on https://developer.sketch.com

**Comment by jedrichards** [comment]
There aren't any immediate plans for publicly accessible Cloud endpoints that work like this, I'm afraid. I'm told maybe in the future, but not now.

Although such an endpoint is simple from the user perspective, Sketch isn't web native so generating the renders in the first place isn't easy and currently requires a lot of infrastructure.

Could you wrap [sketchtool](https://developer.sketch.com/cli/export-assets) in some sort of lightweight service to generate such renders yourself?

Feel free to continue the discussion, I'm just closing the issue to tidy up the issues list 🙂

**Comment by KlausSchaefers** [comment]
Hi, sketchtool runs just on MacOS, correct?

**Comment by jedrichards** [comment]
Yep MacOS only 😕
