### ISSUE TITLE
Where is the Manifest Schema ?

### ISSUE THREAD

**Issue by melMass** [sketch-hq/SketchAPI#788]
Hi,

All links (templates, website, docs) are pointing to:

https://raw.githubusercontent.com/sketch-hq/SketchAPI/develop/docs/sketch-plugin-manifest-schema.json

which does not exist.

**Comment by jedrichards** [comment]
We recently moved the website to a new repo, and looks we didn't handle this JSON file properly.

It was moved [here](https://github.com/sketch-hq/developer.sketch.com/blob/main/sketch-plugin-manifest-schema.json).

We'll fix the website presently, thanks for the report 👍

**Comment by mathieudutour** [comment]
There are another 56 hits (on public repos only): https://github.com/search?q=https%3A%2F%2Fraw.githubusercontent.com%2Fsketch-hq%2FSketchAPI%2Fdevelop%2Fdocs%2Fsketch-plugin-manifest-schema.json&type=Code

**Comment by jedrichards** [comment]
Ah sounds like we should make sure its available on the old url too! 😅

**Comment by melMass** [comment]
Thanks!

**Comment by jedrichards** [comment]
It's back on the old url.
