### ISSUE TITLE
Is there any way to load 3rd-part frameworks on apple silicon?

### ISSUE THREAD

**Issue by margox** [sketch-hq/SketchAPI#841]
I've noticed that the `mocha.loadFrameworkWithName_inDirectory` is not working under the latest version of Sketch on Apple Silicon, our plugin uses this method to import some 3rd-part frameworks such as Sentry and SSZipArchive.

By the way, if I launch Sketch with `use Rosetta2` checked, the `mocha.loadFrameworkWithName_inDirectory` also working, and our plugin works well as expected.

I haven't found any useful information about how to load 3rd-part frameworks in the latest version of sketch, is this impossible now ? :(

**Comment by christianklotz** [comment]
This should be working but it requires that whatever framework you are loading is compiled for Apple Silicon or universal supporting both. You cannot load an x86 framework into a Apple Silicon instance of Sketch.
