### ISSUE TITLE
`SymbolInstance.detach({  recursively: true  })` doesn't work as expected since Sketch 76

### ISSUE THREAD

**Issue by rodionovd** [sketch-hq/SketchAPI#851]
### Summary

After some internal changes in Sketch 76 (mirrored here in 69aa869e56bdfb619cc63b963cd9ba63e17e9b14) the `SymbolInstance.detach()` API now returns an unexpected result: an `NSMapTable` (wrapped by an internal JS class) instead of a `Group` object. It also prints a warning message (_"no mapped wrapper for NSConcreteMapTable"_) to the console. 

### Environment

Sketch 76, 76.1 and 77. A macOS version seems unimportant in this context.

### Reproducing the issue

Here's a (currently failing) test case for this issue:

```js
test('should detach an instance recursively', (_context, document) => {
  const { master } = createSymbolMaster(document)
  const instance = new SymbolInstance({
    symbolId: master.symbolId,
    parent: document.selectedPage,
  })
  expect(instance.type).toBe('SymbolInstance')

  const group = instance.detach({ recursively: true })
  expect(group.type).toBe('Group')
})
```

If we try to print the `group` from the snippet above, we'll see the following:

```js
console.log(group)
// 👉 TypeError: this._object.objectID is not a function. (In 'this._object.objectID()', 'this._object.objectID' is null)
//    at get (/Applications/Sketch.app/Contents/Resources/SketchAPI_dom.js:1:5594)
//    at /Applications/Sketch.app/Contents/Resources/core-modules/@skpm/util/index.js:362:23
//    [...rest of the stack trace...]

console.log(group.sketchObject)
// 👉 <NSConcreteMapTable> NSMapTable {
//      [13] <MSSymbolInstance: 0x7fdbac8e45e0> [...] -> <MSLayerGroup: 0x7fdbac87aad0>[...]
//    }
```

### Workaround

```js
var Group = require('sketch/dom').Group

/// ...
var group = instance.detach({ recursively: true })
/// ...

if (group.sketchObject.isKindOfClass(NSMapTable)) {
  group = Group.fromNative(
    // `group.sketchObject` here maps the original symbol instance to its detached variant
    group.sketchObject.objectForKey(instance.sketchObject)
  )
}
console.log(group)
```

---

Thread on sketchplugins.com: https://sketchplugins.com/d/2413-layerdetachrecursively-true-returns-strange-object

**Comment by lrossi** [comment]
Thanks for the detailed insights. Indeed, there had been a change in the internal methods. The fix has been merged and will be released with the next version of Sketch (78). https://github.com/sketch-hq/SketchAPI/pull/853
