### ISSUE TITLE
APIs missing: remove Flow (prototyping)

### ISSUE THREAD

**Issue by matteogratton** [sketch-hq/SketchAPI#882]
I don't know if this is something that we should just add to the documentation or if we should implement a function to do it.

in order to remove a flow, we currently have to write:
`layer.flow = undefined;`
An option could be to have a function that removes it from the selected layer, as well as the function to remove the layer. Something like:
`layer.flowRemove();`

The way to remove it is missing in the Documentation in any way and I spent time finding it and solved thanks to @lrossi.

**Comment by mathieudutour** [comment]
or just `delete layer.flow` I think, which read really nicely
