### ISSUE TITLE
MSForeignSymbolProvider.alloc().initWithDocument is not a function.

### ISSUE THREAD

**Issue by dewezlopez** [sketch-hq/SketchAPI#902]
Similarly to [Error when calling getImportableTextStyleReferencesForDocument ](https://github.com/sketch-hq/SketchAPI/issues/900), `getImportableSymbolReferencesForDocument` method also produces an error.

Sample code:
```
const sketch = require('sketch')

var onRun = function(context) {
  var document = sketch.getSelectedDocument()
  var libraries = require('sketch/dom').getLibraries()
  library = libraries.find(library => library.name === "MyLibrary")
  var symbolReferences = library.getImportableSymbolReferencesForDocument(
    document
  )
}
```
Error log:

```
TypeError: MSForeignSymbolProvider.alloc().initWithDocument is not a function. (In 'MSForeignSymbolProvider.alloc().initWithDocument(n._getMSDocument())
```

**Comment by bomberstudios** [comment]
Thanks for the report! We have a fix ready for this in Sketch 92, which we’ll release as soon as possible. You can verify the fix on the beta, if needed: https://www.sketch.com/beta/
