### ISSUE TITLE
Error:  'libraryController.libraries' is undefined

### ISSUE THREAD

**Issue by SunilWang** [sketch-hq/SketchAPI#904]
My sketch version is 94

`
TypeError: libraryController.libraries is not a function. (In 'libraryController.libraries()', 'libraryController.libraries' is undefined)
`

How can this problem be solved?

**Comment by rodionovd** [comment]
I believe this Sketch library controller API method has been renamed from `libraries()` to `appLibraries()` in Sketch 94.

If I understand this correctly, Sketch.app (94+) actually bundles a fixed version of the JS API – and the one here on GitHub is outdated (and thus still mentions the old method name).

**Comment by SunilWang** [comment]
@rodionovd Thank you very much, this question has bothered me for a long time!

**Comment by SunilWang** [comment]
SketchApi.js is found in the Sketch installer:
![n_v3395a7d2bef3f4c0a88b109622ac4b524](https://user-images.githubusercontent.com/10388282/200979847-384947ce-b548-43a7-9335-c2b0fc1456db.png)

Now the source code on github:
https://github.com/sketch-hq/SketchAPI/blob/develop/Source/dom/models/Library.js#L43

**Comment by elfenlaid** [comment]
So sorry about that 🙇 Indeed, the public repo ended up in a de-synced state

This PR https://github.com/sketch-hq/SketchAPI/pull/905 synched the changed from the latest Sketch version (v94.1) to the repo

**Comment by SunilWang** [comment]
That seems to have been solved. Thank you very much.
