### ISSUE TITLE
absoluteInfluenceRect() removed in Sketch 96.X

### ISSUE THREAD

**Issue by ronghui1219** [sketch-hq/SketchAPI#915]
Our plugin relies heavily on the absoluteInfluenceRect() method, please add it back? Or is there an alternative?

**Comment by rodionovd** [comment]
Posting the answer here as well for discoverability: https://sketchplugins.com/d/2501-absoluteinfluencerect-removed-in-sketch-96x

CC  https://github.com/sketch-hq/SketchAPI/issues/655

**Comment by ronghui1219** [comment]
> Posting the answer here as well for discoverability: https://sketchplugins.com/d/2501-absoluteinfluencerect-removed-in-sketch-96x
> 
> CC #655

yes, thank you very much , close now
